### ISSUE TITLE
Support jobdeploy

### ISSUE THREAD

**Issue by mikemartin1090** [glg-public/gds-cc-screamer#1]
### Support jobdeploy for GDS
Screamer is currently screaming at me that `jobdeploy` is not a valid line. The check that gets built should also factor in healthcheck and unpublished on the jobs clusters.

### Length of name
I also discovered that the length of the name [can't be as long as 'services' in GDS](https://github.com/glg-public/gds-cc-screamer/blob/fa512cbdc00c2a76c1c8afbc7fc45c1c876f140a/checks/service-name.js#L17-L19). Two options:
1. specify shorter names for gds jobdeploys in the screamer
2. [change the length of this IAM Role Name in the terraform template](https://github.com/glg/terraform-modules/blob/main/gds/aws-ecs-jobdeploy/main.tf#L12)

**Comment by bhudgens** [comment]
This is already an active initiative:

https://app.zenhub.com/workspaces/infrastructure---sre-5d92320acdc7cf0001013e24/issues/glg/metadevops-issues/528

Good catch on role name - New issue on project board here:

https://app.zenhub.com/workspaces/infrastructure---sre-5d92320acdc7cf0001013e24/issues/glg/metadevops-issues/534
