### ISSUE TITLE
Does cc-screamer check glgapp by default?

### ISSUE THREAD

**Issue by mikemartin1090** [glg-public/gds-cc-screamer#119]
# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.p02/pull/3)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.p02/blob/9281f78ee11605bbd9c683ba1833d657163e6f02/call-details/secrets.json#L48)

When cc-screamer is running this check, I see it's claiming this secret does not exist. Maybe it's only checking glgapp? Is it ignoring the account number section of the secret? Something doesn't feel right.

# Result Contents

## ⚠️ Secret Could Not Be Found
- The following secret could not be found: `prod/JWT_SECRET`
- Sometimes this happens because of a stale cache. You can try [refreshing the cache](https://deploy.glgresearch.com/deployinator/enumerate/secrets?bust=true), and then re-running this check suite.

**Comment by shawnrushefsky** [comment]
yes, cc screamer uses deployinator to answer these questions, and deployinator is currently only hooked up in glgapp. Working on fixing that this week

**Comment by shawnrushefsky** [comment]
the deployinator part of this is fixed. need to modify the check to use the account info
