### ISSUE TITLE
Public clusters are supposed to support htpasswd

### ISSUE THREAD

**Issue by datfinesoul** [glg-public/gds-cc-screamer#127]
Public clusters were supposed to have support for htpasswd, and just not have auth on by default.  I believe this must be a mistake.  We still need to address the documentation around this as well, since that is still incorrect.

# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.p01/pull/123)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.p01/blob/95d9a9eb041ab58ed190c91d9f71a6f963576f6a/nodeupperdowner/orders#L19)

# Result Contents

## 💀 Invalid SECURITY_MODE
- This cluster only supports the following security modes: **public**

**Comment by jfungglgroup** [comment]
https://send.glgresearch.com/nodeupperdowner/upper.html has been deployed as expected so that HTPASSWD mode is also working for this public cluster p01.
