### ISSUE TITLE
Unexpected Behavior - not parsing tag with hyphens

### ISSUE THREAD

**Issue by shawnrushefsky** [glg-public/gds-cc-screamer#144]
# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.j01/pull/586)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.j01/blob/35f65f2c71495457c8f434725ff6aa6e97b847c1/capiq-xpressfeed-sync/orders#L12)

# Result Contents

## 💀 Invalid Deployment
- The docker image `github/glg/gds-base-images/main` does not have a tag named `job`
- Sometimes this happens because of a stale cache. You can try [refreshing the cache](https://deploy.glgresearch.com/deployinator/enumerate/ecr/tags?image=github/glg/gds-base-images/main&account=868468680417&bust=true), and then re-running this check suite.
- [More About Deploying To GDS](https://services.glgresearch.com/know/glg-deployment-system-gds/deploying-a-service/)

**Comment by ddai1** [comment]
This will be happened for both dockerdeploy and jobdeploy as they both are in same format of github/<org>/<repo>/<branch>:<tag>
