### ISSUE TITLE
JSON flagged as possible secret

### ISSUE THREAD

**Issue by trevorr** [glg-public/gds-cc-screamer#145]
JSON containing no secrets (only low entropy numbers and strings) is being flagged as a secret. Ideally, the screamer would try to recognize JSON objects, parse them, and check their values for strings containing secrets.

# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.p02/pull/8)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.p02/blob/13acade07436e64a8b459adaf14d9ac2c05b6a94/call-details-header-test/orders)

# Result Contents

## ⚠️ Possible Secret?
- Problem existed outside of diff at `call-details-header-test/orders`, line **18**
- This looks like it might be a secret. You should probably store this in AWS Secrets Manager.
- This was flagged as `isStrongPassword`. If this is definitely not a secret, disregard.

**Comment by shawnrushefsky** [comment]
Oddly, it is already supposed to skip json objects: https://github.com/glg-public/gds-cc-screamer/blob/main/checks/potential-secrets.js#L140 . I'll try to figure out whats going on
