### ISSUE TITLE
Unexpected Behavior

### ISSUE THREAD

**Issue by david0178418** [glg-public/gds-cc-screamer#168]
![image](https://user-images.githubusercontent.com/128739/155402969-bd53e84a-4f9f-4b75-8ca9-52fda568db49.png)

# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.s01/pull/467)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.s01/blob/10ef0bafb08e2bb42e3cd917e8ba27517ce2f468/availability/orders#L34)

# Result Contents

## ⚠️ Possible Secret?
- This looks like it might be a secret. You should probably store this in AWS Secrets Manager.
- This was flagged as `highEntropy`. If this is definitely not a secret, disregard.

**Comment by shawnrushefsky** [comment]
How would you recommend identifying that as not a secret?

**Comment by david0178418** [comment]
I've got no recommendation.  I just clicked the "Look wrong?" link.

**Comment by shawnrushefsky** [comment]
ok. I'm going to close this then, because it's non-blocking and says "If this is definitely not a secret, disregard.". It is a high entropy string.
