### ISSUE TITLE
If ote_locks mechanism is detected, make sure policy is in place

### ISSUE THREAD

**Issue by mikemartin1090** [glg-public/gds-cc-screamer#193]
On this PR, the user created the orders file but forgot to put a policy that allowed the use of the ote_locks table. We should either warn them or fail them based on use cases. Some logic I can think of: if gds-base-images is used AND there is a cron statement and a job, then you should have a policy.json that allows the locking.

https://github.com/glg/gds.clusterconfig.j01/pull/812/files

**Comment by cwebster2** [comment]
Issue moved to https://github.com/glg/gds-cc-screamer/issues/6
