### ISSUE TITLE
validate cron expressions

### ISSUE THREAD

**Issue by mikemartin1090** [glg-public/gds-cc-screamer#209]
I've been seeing a number of `Error: error updating CloudWatch Events Rule (v1-i03-survey-associate-recurring-scheduled-task-event-rule): ValidationException: Parameter ScheduleExpression is not valid.` in the logs. Lets flag these for our users so they don't have to wait for a failure.

https://github.com/glg/gds.clusterconfig.i03/pull/820/files as an example.

**Comment by shawnrushefsky** [comment]
We do validate cron expressions, so this may be a bug in how ccwatcher translates standard cron to aws cron
