### ISSUE TITLE
What is this even complaining about?

### ISSUE THREAD

**Issue by squince** [glg-public/gds-cc-screamer#228]
# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.i03/pull/977)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.i03/blob/7d05f9a292d75fbb36058a457acf9f539d33819f/client-integration-api/orders)

# Result Contents

## ⚠️ Debug In Production
- Problem existed outside of diff at `client-integration-api/orders`, line **17**
- Did you mean to leave this configured this way in production?

**Comment by shawnrushefsky** [comment]
The error is inappropriate for the testing cluster, so I'll disable it there. It is telling you you are deploying a service with debug logging enabled, which most people don't want to do in production
