### ISSUE TITLE
Some variables are free and can be relied upon in the env

### ISSUE THREAD

**Issue by shawnrushefsky** [glg-public/gds-cc-screamer#232]
ORDERS_NAME is a freebie.

# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.s01/pull/714)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.s01/blob/87ce52e168bd6ec0c2c4d3d6a46df8ee4f82c721/jupyterhub-erbi-test/orders)

# Result Contents

## 💀 Out of Scope Variable Reference
- Problem existed outside of diff at `jupyterhub-erbi-test/orders`, line **8**
- GDS requires that all referenced variables be defined within the `orders` file. `.starphleet` has been deprecated.
- **Undefined Variable:** `ORDERS_NAME`

**Comment by cwebster2** [comment]
Issue moved to https://github.com/glg/gds-cc-screamer/issues/9
