### ISSUE TITLE
monorepo paths not supported

### ISSUE THREAD

**Issue by stovenator** [glg-public/gds-cc-screamer#236]
# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.i22/pull/110)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.i22/blob/329c215cc2bbe72f484a67ae3293ae1cbdce226e/shell-api/orders#L29)

# Result Contents

## 💀 Invalid Deployment
- **apps/shell-api/main** - Branch name must be only lowercase alphanumeric characters and hyphens. [Reason: AWS Restrictions](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_Repository.html)

**Comment by shawnrushefsky** [comment]
We need to update tooling to support some of the new monorepo stuff. Working on it presently.

**Comment by mikemartin1090** [comment]
Will need to leverage [this helper](https://github.com/glg/ecr-registration-lambda/blob/2bcdc5979b6d8d3f277eeb595e0a52154b5a19bb/lib.js#L124-L129) to put their matrix back together.
