### ISSUE TITLE
Unexpected Behavior

### ISSUE THREAD

**Issue by AlexisJackson** [glg-public/gds-cc-screamer#237]
# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.s01/pull/734)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.s01/blob/3b0c9923c38b2c5a3149e5598276768c5710f0aa/zendesk-project-scheduling/orders)

# Result Contents

## ⚠️ Possible Secret?
- Problem existed outside of diff at `zendesk-project-scheduling/orders`, line **27**
- This looks like it might be a secret. You should probably store this in AWS Secrets Manager.
- This was flagged as `highEntropy`. If this is definitely not a secret, update `.ccscreamer.json` to include the following:
```json
{
  "zendesk-project-scheduling": {
    "potentialSecrets": {
      "exclusions": [
        "REACT_APP_PATH"
      ]
    }
  }
}
```
[Documentation](https://github.com/glg-public/gds-cc-screamer#potentialsecretsexclusions)

**Comment by shawnrushefsky** [comment]
We need a `isAFilePath` exception in `potentialSecrets`

**Comment by cwebster2** [comment]
Isssue moved to  https://github.com/glg/gds-cc-screamer/issues/10
