### ISSUE TITLE
Don't allow jobs to run on less than 5 minute increments

### ISSUE THREAD

**Issue by mikemartin1090** [glg-public/gds-cc-screamer#240]
There was an incident on Friday July 29, 2022 where there were too many tasks running at once, primarily due to jobs scheduled to run every minute. It's been determined that a job that runs every minute is no longer a job, but should probably be considered a service.

Lets setup a guard that does not allow engineers to schedule tasks with smaller than 5 minutes increments.

**Comment by cwebster2** [comment]
Issue moved to https://github.com/glg/gds-cc-screamer/issues/13
