### ISSUE TITLE
dockerdeploy path inconsistency between dev and production

### ISSUE THREAD

**Issue by dhunt787** [glg-public/gds-cc-screamer#243]
# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.s09/pull/490)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.s09/blob/c2da42c73a4e57a2c6e30014563799ff5de632a6/home-api/orders#L27)

# Result Contents

## 💀 Invalid Deployment
- **apps/home-api/main** - Branch name must be only lowercase alphanumeric characters and hyphens. [Reason: AWS Restrictions](https://docs.aws.amazon.com/AmazonECR/latest/APIReference/API_Repository.html)

CC-screamer does not highlight this as an issue on dev/internal clusters. We use this path for the dockerdeploy command in a few files on the i22 cluster and it did not cause issues apparently (I did not personally create those order files/PRS)

**Comment by ddai1** [comment]
The name of repo and branch name must be only lowercase alphanumeric characters and hyphens. Your deployment can be fixed by having the branch name renamed.
