### ISSUE TITLE
Warn on presence of PATHS_OF_OTHER_BETAS variable

### ISSUE THREAD

**Issue by drhayes** [glg-public/gds-cc-screamer#253]
When copying orders in deployinator sometimes the beta paths come along for the ride. We often don't want that. We should warn on the presence of that environment in the CC PR check.

Here's the corresponding issue on the deployinator side: https://github.com/glg/deployinator/issues/225

**Comment by cwebster2** [comment]
Issue moved to https://github.com/glg/gds-cc-screamer/issues/2
