### ISSUE TITLE
Error running check: check is not a function ?

### ISSUE THREAD

**Issue by mikemartin1090** [glg-public/gds-cc-screamer#255]
Not sure why I got this, but here it is!

```
check is not a function

TypeError: check is not a function
    at run (/home/runner/work/_actions/glg-public/gds-cc-screamer/main/index.js:193:27)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Here are the logs of where it happened! https://github.com/glg/gds.clusterconfig.i01/runs/8233388828?check_suite_focus=true#step:3:20

**Comment by cwebster2** [comment]
Issue moved to https://github.com/glg/gds-cc-screamer/issues/16
