### ISSUE TITLE
Further validate deployment line!

### ISSUE THREAD

**Issue by drhayes** [glg-public/gds-cc-screamer#27]
If an `autodeploy`, does the repo and branch exist? If `dockerdeploy`, is that docker image in the repository with that tag? Etc.

**Comment by shawnrushefsky** [comment]
Requirements:

- [ ] github token with read access to all repos
- [ ] aws creds that can list image tags
- [ ] probably terraform that injects these things into clusterconfig repo secrets
- [ ] should just skip if the extra creds aren't present (since this is a public repo)

**Comment by shawnrushefsky** [comment]
This can actually just use deployinator to get this info. CC Screamer now has an app token available to it in clusterconfig repos
