### ISSUE TITLE
Reserved Variables Not Usable in secrets.json

### ISSUE THREAD

**Issue by bhudgens** [glg-public/gds-cc-screamer#28]
### Summary

Users cannot see which ENV variables we use internally to GDS. There's not really a programmatic way to get to them either. Fortunately, there are not too many of them. Thus, I'm okay with us statically baking them into a list in CC-Screamer so that deployinator -and- cc-screamer respect this list.  Ultimately, I need for users to not be able to set their environment variable name to the same thing as one of our internally used variables.

Here's an example:

https://github.com/glg/gds.clusterconfig.j01/commit/4969d9ef34fce99849c85f0ce71fcdfaf0d62c10

TF Error:

![image](https://user-images.githubusercontent.com/7997948/110586272-8fc26c00-8137-11eb-8769-515bb086f1d6.png)

Once this mechanism exists in CC-Screamer, we can come back to this and polish the list of variables that should be reserved and not usable in the secrets.json

**Comment by shawnrushefsky** [comment]
This is now in CC Screamer: https://github.com/glg-public/gds-cc-screamer/blob/main/checks/no-reserved-vars.js#L5-L37
