### ISSUE TITLE
Unexpected Behavior

### ISSUE THREAD

**Issue by asegal** [glg-public/gds-cc-screamer#44]
# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.i03/pull/3)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.i03/blob/7efc3d64bb17cb5cc7e643391a1cdc9fcd1ced42/cx-services/orders#L10)

# Result Contents

## ⚠️ Possible Secret?
- This looks like it might be a secret. You should probably store this in AWS Secrets Manager.
- This was flagged as `highEntropy`. If this is definitely not a secret, disregard.

**Comment by shawnrushefsky** [comment]
This was flagged because of the space at the end of the URL. Correctly formed URLs do not have this problem
