### ISSUE TITLE
We want to change the PATH inside the container

### ISSUE THREAD

**Issue by mikemartin1090** [glg-public/gds-cc-screamer#59]
# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.j01/pull/56)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.j01/blob/6fa76a4d97a17b7f0aa05a32a76890f1e4290870/remailer-notify-cs-rec-inv/orders#L17)

# Result Contents

## 💀 Out of Scope Variable Reference
- GDS requires that all referenced variables be defined within the `orders` file. `.starphleet` has been deprecated.
- **Undefined Variable:** `PATH`

We want to change the PATH within the container and do realize there is no .starphleet any longer. Should this be fixed?

**Comment by shawnrushefsky** [comment]
That's a good point. Maybe we should exclude some things you get for free in linux, like $PATH and $HOME

**Comment by shawnrushefsky** [comment]
solved by #63
