### ISSUE TITLE
Unexpected Behavior - says secret is not found

### ISSUE THREAD

**Issue by fearphage** [glg-public/gds-cc-screamer#61]
# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.j01/pull/62)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.j01/blob/3d38ff895b5ed5e874ab34372811e6c2f99a6864/hq-stale-process/secrets.json#L4)

# Result Contents

## ⚠️ Secret Could Not Be Found
- The following secret could not be found: `us-east-1/production/GITHUB_SVCGITHUBSTALEBOT_API_TOKEN`

![image](https://user-images.githubusercontent.com/23887/121203553-cf364c80-c83b-11eb-8150-cc56b51a9576.png)

**Comment by shawnrushefsky** [comment]
marking this closed. If this wasn't due to a stale cache, it may have been due to an expired cc screamer app token. both have been addressed.
