### ISSUE TITLE
Unexpected Behavior - doesn't recognize secrets with `-??????` suffice on the end.

### ISSUE THREAD

**Issue by fearphage** [glg-public/gds-cc-screamer#68]
# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.j01/pull/163)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.j01/blob/e15841691af3265a219017a1b9085cece0dd611d/contact-resync-e160482/policy.json#L21)

# Result Contents

## 💀 Policy is missing required secrets
- Your secrets.json requests arn:aws:secretsmanager:us-east-1:868468680417:secret:us-east-1/production/S3_WRITE_ACCESS_glg-expire-after-30-days_contact-resync, but your policy does not allow access.
- Add the following statement block
```suggestion
    },
    {
      "Sid": "AllowSecretsAccess1",
      "Effect": "Allow",
      "Action": "secretsmanager:GetSecretValue",
      "Resource": [
        "arn:aws:secretsmanager:us-east-1:868468680417:secret:us-east-1/production/S3_WRITE_ACCESS_glg-expire-after-30-days_contact-resync"
      ]
    }
```

**Comment by shawnrushefsky** [comment]
solved by #69
