### ISSUE TITLE
cc-screamer is being rate limited

### ISSUE THREAD

**Issue by fearphage** [glg-public/gds-cc-screamer#70]
https://github.com/glg/gds.clusterconfig.j01/runs/2840283651?check_suite_focus=true#step:3:166

**Comment by shawnrushefsky** [comment]
wow. yeah, I guess if a single run has too many errors. I guess the fix would be to check if `numProblems > n` and if so, maybe post summary comments or something else that would reduce how many comments need to be left.

**Comment by fearphage** [comment]
Another https://github.com/glg/gds.clusterconfig.j01/pull/179#issuecomment-862654759
