### ISSUE TITLE
Email address flagged as possible secret

### ISSUE THREAD

**Issue by matteozambon89** [glg-public/gds-cc-screamer#78]
# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.j03/pull/76)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.j03/blob/d1e5b169635d3fd1427f6d1f2b500ce0c23bb19e/invoicerizer-min-commitment/orders#L15)

# Result Contents

## ⚠️ Possible Secret?
- This looks like it might be a secret. You should probably store this in AWS Secrets Manager.
- This was flagged as `highEntropy`. If this is definitely not a secret, disregard.

# Pattern

```
To<email@domain.com>
```

**Comment by shawnrushefsky** [comment]
fwiw, bare emails like `email@domain.com` don't get flagged.

>If this is definitely not a secret, disregard.
