### ISSUE TITLE
Email list is flagged as potential secret

### ISSUE THREAD

**Issue by matteozambon89** [glg-public/gds-cc-screamer#79]
# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.j03/pull/76)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.j03/blob/d1e5b169635d3fd1427f6d1f2b500ce0c23bb19e/invoicerizer-min-commitment/orders#L17)

# Result Contents

## ⚠️ Possible Secret?
- This looks like it might be a secret. You should probably store this in AWS Secrets Manager.
- This was flagged as `highEntropy`. If this is definitely not a secret, disregard.

# Pattern

```
email00@domain.com,email01@domain.com,email03@domain.com
```

also

```
email00@domain.com;email01@domain.com;email03@domain.com
```

**Comment by shawnrushefsky** [comment]
yeah, there's really no way to catch every possible scenario. That's why this one's a "warn" and isn't blocking.
>If this is definitely not a secret, disregard.
