### ISSUE TITLE
Unexpected Behavior - jobs clusters limited to 100 services

### ISSUE THREAD

**Issue by fearphage** [glg-public/gds-cc-screamer#80]
# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.j01/pull/240)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.j01/blob/396067eb585fe2bf9e020348cc8299c1d38c4c24/events-rec-main-compute/orders)

# Result Contents

## 💀 Too Many Services In This Cluster
- This cluster supports a maximum of 100 services. (Currently **116** services, including `/events-rec-main-compute`)

**Comment by shawnrushefsky** [comment]
oh yeah! that's an ALB limit, which doesn't apply to jobs clusters
