### ISSUE TITLE
Unexpected Behavior

### ISSUE THREAD

**Issue by beldougie** [glg-public/gds-cc-screamer#83]
# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.j01/pull/246)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.j01/blob/ea52dbecaffbf43981709e2bae2fbc734b44455a/invoicerizer/orders)

# Result Contents

## ⚠️ Possible Secret?
- Problem existed outside of diff at `invoicerizer/orders`, line **22**
- This looks like it might be a secret. You should probably store this in AWS Secrets Manager.
- This was flagged as `isStrongPassword`. If this is definitely not a secret, disregard.

This is a little over-zealous, it is identifying emails and/or lists of emails as secrets/passwords.

**Comment by shawnrushefsky** [comment]
That's why it's a warning, and not a blocker
