### ISSUE TITLE
Flagged my `cron` comment despite it being correct.

### ISSUE THREAD

**Issue by drhayes** [glg-public/gds-cc-screamer#89]
# Context
- [Pull Request](https://github.com/glg/gds.clusterconfig.j01/pull/332)
- [Flagged Lines](https://github.com/glg/gds.clusterconfig.j01/blob/078ad76d9ee29e85fd92dc1ec183eec2f216b6d8/log-roller/orders)

# Result Contents

## 👉 Update This Comment
- Problem existed outside of diff at `log-roller/orders`, line **35**
- Update This Comment
```suggestion
# At 11 minutes past the hour (UTC)
```

**Comment by shawnrushefsky** [comment]
Oh, yeah, it isn't semantically parsing the comment, it just generates a comment based on the cron, and then diffs it. That's why it's only an info-level comment, and isn't blocking.
