### ISSUE TITLE
AWS account id flagged as sensitive

### ISSUE THREAD

**Issue by cwebster2** [glg-public/gds-cc-screamer#93]
The check: https://github.com/glg/gds.clusterconfig.s01/pull/192/checks?check_run_id=3375891598
![image](https://user-images.githubusercontent.com/5762261/130266558-1bc9b324-4bfd-440b-a6a7-e1f25625a326.png)

And the offending line https://github.com/glg/gds.clusterconfig.s01/blob/88ac56882adb5fe37d2658b76d1d2da9396d51f1/cli-provisioner-api/orders#L21

AWS account numbers should not be flagged as secrets.

**Comment by shawnrushefsky** [comment]
This is actually a starscream issue and not a cc-screamer issue
